---
title: 'EuADS Summer School 2019: SUBJECTIVITY and VISUALIZATION'
author: Muhammad Chenariyan Nakhaee
date: '2020-01-04'
slug: []
categories:
  - XAI
tags:
  - XAI
  - Visualization
subtitle: ''
summary: ''
authors: []
lastmod: '2020-01-04T14:28:27+01:00'
featured: no
image:
  caption: ''
  focal_point: ''
  preview_only: no
projects: []
---



This talk was mainly focused on the importance of visualization and other techniques for exploring and explaining data.  In other words,  one approach to explainability is to first explore the input data and find interesting patterns. This can be done via:

- Association analysis ()
- Dimensionality reduction techniques
- Graph embeddings
- Clustering
- Community detection 
- ...

However interesting pattern is a subjective term and there are a huge number of "interesting measures" out there. What you find interesting as a data mining researcher may be different from another researcher.   For example, in the case of community detection what we can define as an interesting community can vary. An  interesting community might be a densely connected set of nodes or a set of nodes that have few outside neighbors.

Why interestingness measures are subjective? Because as a user we compare patterns with our prior beliefs or expectations and in if a pattern <span style="color:blue"> contrasts</span> with them and <span style="color:blue"> can be described easily</span>, we consider it as interesting.

The challenge is to come up with a metric or formalize a metric that measures 'true interestingness" for us.

